### ISSUE TITLE
Research graduate work on MsSqlServer for linux

### ISSUE THREAD

**Issue by cwdlcs** [woachk/drawbridge#1]
Hello, woachk! Sorry for writing here, but it seems to be the only way to contact you. I cannot find your e-mail over the all internet. I'm doing my graduation work for researching MSSqlServer for Linux, and found something intersting in your repository. Please, contact me

**Comment by woachk** [comment]
Hi,

I think that it'd be better to just put your question publicly here.

Thanks,

**Comment by cwdlcs** [comment]
I don’t think that a good idea, because it needs to write many details, but i’ll try. So.. I have ms sql server 2017 for Linux (downloaded from msdn), running on Ubuntu 18.04. The goal of my research - try to run another application in drawbridge. Now I have got sfp unpacker from github, and have written the sfp packer. I have patched sqlservr not to check checksum of sfp containers. So, have u got any ideas, how to run another application instead of (or with) sql server?

**Comment by cwdlcs** [comment]
Of course, I have tried to put simple “hello world” into sqlserver.sfp, renamed it as sqlservr.exe, changed the manifest file, but in crashes on loading with error, that apploader.exe returned wrong code

**Comment by woachk** [comment]
Hi, 

At first, put your binary in /var/opt/mssql/data/xtp/, it's a whitelisted path (indicated in the sqlservr.sfp manifest) to run binaries outside of the sandbox. See the initial.sh and palrun shell scripts, and change the path to the one of your executable in config.ini (Entrypoint setting).

Also, can you open-source your SFP packer? It'd make debugging your issue easier.

Thanks,

**Comment by cwdlcs** [comment]
Thank u a lot. I will try it tomorrow.
But where I can find initial.sh and Palrun scripts, and config.ini? There aren’t such ones in sqlserver package..

Sorry, but I can’t open-source sources of sfppacker now, because it’s part of my graduation. I can only publish an .exe binary of sfppacker. After May,30 I will open-source all of it. Thank u

**Comment by woachk** [comment]
Hi, 

They're part of this GitHub repository, at its root even. :)

About the SFP packer then, I should open-source it. Btw, patching the PAL to remove checksum checking is a bad choice, you should compute the checksum instead.

Also, I think that it's already a quite well explored and understood subject, and that choosing it might not be the right choice, especially as the tools to do so are public on this repository. :)

Thanks,

**Comment by cwdlcs** [comment]
I found them, but where I should put them on my test VM with Ubuntu SQL server? Or I misunderstood something?

I’ve spent a lot of time disassembling sqlserver to find out or restore algorithm of calculating checksum, but it was unsuccessfully.

About choosing the graduation theme- running other application in pal - very small part of research. The most part dedicated to develop full network stack for pal system, as it works on dockers. It needs to clasterize some windows applications:)

**Comment by woachk** [comment]
@cwdlcs 

git clone https://github.com/woachk/drawbridge  
cd drawbridge
./initial.sh
modify path in config.ini
./palrun

Ok, will write up about the algorithm later, it's a 16-bit checksum. (or just release the source)

Thanks,

**Comment by cwdlcs** [comment]
Thank u a lot. I will try it tomorrow, it obviously need to research deeper.
The main problem now is that I need to download your repository, put and changes something there. But the way, perfectly, I need to do smth with downloaded package to run other code inside of it.

Also, about the algorithm, it would be better, if you write up algorithm without source.
People need to develop something, not only use stackoverflow or github ctrl+c/crtl+v ;))
Thank u a lot

**Comment by cwdlcs** [comment]
@woachk Hi again :)
I've tried the way you recommended. Also that I did:
1. Cloned your repo into cleare ubuntu with MSSql server
2. Exec initial.sh
3. Copy my simple exe. which is look like:
```
#include <fstream>
int main(int argc, char* argv[])
{
	ofstream fout("testfilecreated.txt");
	fout << "I'm working under SQLPAL";
	fout.close();
	return 0;
}
```
4. changed the "Application.Settings" section in config.ini
5. exec the palrun
But in crashed with such log:
```
./palrun
This is an evaluation version.  There are [62] days left in the evaluation period.
** ERROR: [AppLoader] Failed to launch app: 0x2
AppLoader: Exiting with status=0xc0070002
This program has encountered a fatal error and cannot continue running at Sun Mar  3 23:24:52 2019
The following diagnostic information is available:

       Reason: 0x00000006
       Status: 0xc0000001
      Message: Termination of \SystemRoot\system32\AppLoader.exe was due to fatal error 0xC0000001
      Address: 0x6a4b9cfa
   Stacktrace: 000000006a57d75f 000000006a4b9bb5 000000006a4b9cfa 
               000000006a4b90b8 000000006a4b919b 000000006a5af65b 
               000000006a5af704 0000000300064010 
      Process: 11792 - sqlservr
       Thread: 11823 (application thread 0x70)
  Instance Id: 72d1b509-0f27-45ac-a548-37e6f799d95b
     Crash Id: 58f5917a-30e0-452e-a70a-df27fd6d3c53
  Build stamp: ac23850f3eced1a7a4dac98dd60a61b565747910d2f2aaea8c639c5d1ba0bcb0
*********** PAL PANIC CORE DUMP GENERATION FAILED **********
Unable to locate handle-crash.sh. Error 2.
*********** PANIC CORE DUMP GENERATION FAILED **********
Attempt to launch handle-crash.sh failed with error 0x00000002 
```
I can't find anything debug information about this error.
Have you any ideas, how to debug it?

Also, i've understood, that your scripts run the application, that is dislocated outside the sandbox, and so it should working outside the sandbox. Have you any ideas, how to put it IN the sandbox and start it there?
Thanks.

**Comment by woachk** [comment]
@cwdlcs did you copy your app somewhere into /var/opt/mssql/data/xtp/?

**Comment by cwdlcs** [comment]
@woachk, nope, I put it in the root of xtp directory

**Comment by woachk** [comment]
@cwdlcs copy your app to /var/opt/mssql/data/xtp and don't forget to either link using /MT or copy over the VS DLLs

**Comment by cwdlcs** [comment]
@woachk I have copied it already into /var.../xtp directory. Also, the app was built on VS 2013 with MT flag, but it still not working

**Comment by woachk** [comment]
@cwdlcs did you use the latest SQLS2017 CU?

**Comment by cwdlcs** [comment]
@woachk, ofc, last available on msdn for offline install. It is 15.0.1100.94-1_amd64.deb package with all dependencies installed

**Comment by woachk** [comment]
@cwdlcs can you upload your sqlservr binary + system.sfp?

**Comment by woachk** [comment]
@cwdlcs repo going to be deleted, contact at msm123@outlook.com
